### ISSUE TITLE
Still working for current CiviCRM (4.7.19) ?

### ISSUE THREAD

**Issue by magnolia61** [MegaphoneJon/coop.palantetech.nodrilldown#1]
Hi Jon,
Quite some months ago I have used this extension successfully.
Just to notice it does not seem to work anymore. Can you confirm it still works for CiviCRM 4.7.19?
```
$pattern = '/\/civicrm\/report\/instance\/\d*\?reset=1&amp;force=1&amp;id_op=eq&amp;id_value=/';
https://www.ourdomain.nl/civicrm/report/instance/2?reset=1&force=1&id_op=eq&id_value=5614
```
Regards, Richard

**Comment by MegaphoneJon** [comment]
Hi @magnolia61 - I'm glad to hear others are using this!  I haven't tested this recently at all.  I'll give it a shot soon and update it as necessary.  Feel free to do it sooner if you get an opportunity!

**Comment by wintermoor** [comment]
Hi @PalenteJon - this is awesome! I disliked the idea to click a link and don't get directly to the contact, too. 

Unfortunately, it's not working on my fresh Drupal install with CiviCRM 4.7.22. Installation went well, everything is on "green". I'm feeling a little bit helpless now - as a newbie :) 

Do you know advice? 

Best 
Torben

**Comment by MegaphoneJon** [comment]
Hi @wintermoor - I'm pretty sure this needs a fix, but you know how it is with unpaid work.  It's on my radar though - hopefully this month!

**Comment by MegaphoneJon** [comment]
@wintermoor @magnolia61 I just tested this on the master branch with the Sybunt report, and it seems to be working fine for me.  Could you please update this with a specific report that's not working for you?

**Comment by MegaphoneJon** [comment]
Hi Richard and Torben - I haven't heard back in a little over a week, so while I'm sure there are some reports that may not be working anymore with this extension, I have no idea which they are.  I'm going to close this until such time as someone can tell me which reports to look at!

**Comment by magnolia61** [comment]
Hi Jon,
I just checked which report didn't work for me and it seems to be the "Event Participant Report (List)" that I mainly use. If it's easy and when you have time it would really help us a lot! :-) Thanks for this great extension! Cheers, Richard

**Comment by MegaphoneJon** [comment]
Ah, thank you @magnolia61! I'm not sure that report was ever working with this extension.  I've just tagged a new release that fixes this - hopefully in the next day or so your Civi will notify you that there's a new release to update to.

**Comment by wintermoor** [comment]
New install on Ubuntu 16.04 doesn't show this misbehaviour. Only CentOS 7. Thx a lot for this extension!
