### ISSUE TITLE
URL pattern and replacement for WordPress installations

### ISSUE THREAD

**Issue by mwestergaard** [MegaphoneJon/coop.palantetech.nodrilldown#2]
Per Jon's request, I'm submitting this issue for WordPress support. Civi's URLs under WordPress differ. In nodrilldown.php I used:

```
/*
$pattern = '/\/civicrm\/report\/instance\/\d*\?reset=1&amp;force=1&amp;id_op=eq&amp;id_value=/';
$replace = '/civicrm/contact/view?reset=1&cid=';
*/
$pattern = '/\=civicrm\/report\/instance\/\d*&amp;reset=1&amp;force=1&amp;id_op=eq&amp;id_value=/';
$replace = '=civicrm/contact/view&reset=1&cid=';

```
For example, View Contact is:
`http://myhost.org/wp-admin/admin.php?page=CiviCRM&q=civicrm/contact/view&reset=1&cid=2`

**Comment by MegaphoneJon** [comment]
I just tagged a new release which should support both WordPress and non-WordPress CMSes.  Thanks for your report!

**Comment by mwestergaard** [comment]
I had to update again for WordPress. I just noticed the issue, so it may have been caused by the WordPress 5.0 update. Here are my inelegant changes:

```
<     $pattern = '/civicrm\/report\/instance\/\d*(\?|&amp;)reset=1&amp;force=1&amp;id_op=eq&amp;id_value=/';
---
>     $pattern = '/civicrm(\/|%2F)report(\/|%2F)instance(\/|%2F)\d*(\?|&amp;|&)reset=1(&amp;|&)force=1(&amp;|&)id_op=eq(&amp;|&)id_value=/';
```
