### ISSUE TITLE
Links not changing on latest WordPress and CiviCRM Install

### ISSUE THREAD

**Issue by encircle** [MegaphoneJon/coop.palantetech.nodrilldown#3]
Hi Jon, I've installed your extension on latest WordPress (5.4) and CiviCRM (5.24.3) but the report links don't seem to be updated. They are still linking to the detail report.

Would you have anytime to look into this? I can provide access to our dev environment if it helps.

Many thnaks,
Darren

**Comment by encircle** [comment]
Oops! just noticed the last comment on the fixed issue.... I've replaced the replace with the correct values for wordpress:-

$replace = 'civicrm/contact/view&reset=1&cid=';

**Comment by MegaphoneJon** [comment]
Hi Darren - I think you're saying it's OK to close this issue?  I'll admit I don't think about this extension very often.
