### ISSUE TITLE
Doesn't work for the Lapsed Membership Report

### ISSUE THREAD

**Issue by yosefromano** [MegaphoneJon/coop.palantetech.nodrilldown#4]
Great extension!
The extension doesn't seem to work in CiviCRM core's lapsed membership report.

**Comment by MegaphoneJon** [comment]
What version and CMS are you using?

**Comment by MegaphoneJon** [comment]
To be clear - there's no standard (or rather, there are several standards) for how drill-down is implemented in CiviReport, so the extension has to be told how to handle each report individually.  It's totally possible I missed one.

**Comment by yosefromano** [comment]
Currently on Drupal 7.69 and CiviCRM 5.20.3
Ah interesting, I didn't realize it was report specific.

**Comment by MegaphoneJon** [comment]
Hi Yossi,

I just tagged a new release 1.1.3 to address this.  I'm not sure if the civicrm.org extension directory will pick up the change, they're in the middle of upgrading - but if you don't get a notification in Civi to upgrade, you can always download manually.

**Comment by yosefromano** [comment]
@MegaphoneJon Works amazing! Thank you
