### ISSUE TITLE
Wordpress URL pattern

### ISSUE THREAD

**Issue by mwestergaard** [MegaphoneJon/coop.palantetech.nodrilldown#5]
I had to reapply this change for Wordpress 5: https://github.com/MegaphoneJon/coop.palantetech.nodrilldown/issues/2

**Comment by encircle** [comment]
Thanks @mwestergaard that's fixed this regression bug for us too.

**Comment by MegaphoneJon** [comment]
Thanks for the heads-up @mwestergaard!  @megaphonetech-dennis created PR #6 based on this, and I've just tagged a new release with your fix.
